// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel UpdateParticles

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
// RWTexture2D<float4> Result;
RWBuffer<particle> Result;

[numthreads(8,8,1)]
struct particle
{
    float2 _position;
    float2 _direction;
    float2 _size;
}
void UpdateParticles (uint3 id : SV_DispatchThreadID)
{

}
